config/routes.rb
Videothek::Application.routes.draw do
  resources :rentals
  match "/films/add_new_rental" => "films#add_new_rental", :as =>
"add_new_rental_to_users", :via => [:post]

  post '/rate' => 'rater#create', :as => 'rate'
  

	devise_for :users, controllers: {registrations: "registrations"}
		
	resources :maintopics do
		resources :subtopics
	end

  resources :comments

  resources :films
  get '/search' => 'films#search'
  
  match "/films/add_new_comment" => "films#add_new_comment", :as => "add_new_comment_to_films", :via => [:post]

	root to: 'films#index'

end

app/models/film.rb
class Film < ActiveRecord::Base
validates_uniqueness_of :title, :scope => :release_date
has_many :film_categories
has_many :categories, through: :film_categories

has_many :comments
has_many :users, through: :comments

has_many :film_actors
has_many :actors, through: :film_actors

has_many :film_directors
has_many :directors, through: :film_directors

has_many :rentals
has_many :users, through: :rentals

letsrate_rateable "rating"
acts_as_commentable

resourcify
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
skip_before_filter :verify_authenticity_token

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  def add_new_rental
    film = Film.find(params[:id])
    rent = {:film_id => film, :user_id => current_user.id}
    film.rentals.create(rent)
    redirect_to rentals_url
    end

  def add_new_comment
    film = Film.find(params[:id])
    ca = {:title => params[:comment][:title], :comment => params[:comment][:comment], :user_id => current_user.id}
    film.comments.create(ca)
    redirect_to :action => :show, :id => film
  end  
private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :runtime, :cover, :release_date, :plot)
    end

end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :runtime %><br>
    <%= f.number_field :runtime %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.text_field :cover %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :plot %><br>
    <%= f.text_area :plot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Liste der Filme</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Runtime</th>
      <!-- <th>Cover</th> -->
      <th>Release date</th>
      <!-- <th>Plot</th> -->
      <th>Rating</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.runtime %></td>
        <!-- <td><%= film.cover %></td> -->
        <td><%= film.release_date %></td>
        <!-- <td><%= film.plot %></td> -->
	<td><%= rating_for film, "rating" %></td>
        <td><%= link_to 'Show', film %></td>
	

		<% if user_session != nil %>
			<% if current_user.has_role? :admin %>
    		<td><%= link_to 'Edit', edit_film_path(film) %></td>
		<% end %>
		<% end %>

		<% if user_session != nil %>
			<% if current_user.has_role? :admin %>
    	<td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	 	<% end %>
		<% end %>
		  
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<br><br>

  <% if user_session != nil %>
    <% if current_user.has_role? :admin %>
  <%= link_to 'New Film', new_film_path %>
  <% end %><% end %>



<% if current_user == nil%>
Damit Sie bewerten können, müssen Sie sich einloggen. <br>
<%= link_to 'Sign in', new_user_session_path %>
<%= link_to 'Sign up', new_user_registration_path %>
<% end %>


<!--
<% if current_user %>
Logged in as: <%= current_user.email %>
<% else %>
Damit Sie bewerten können, müssen Sie sich einloggen.
<%= link_to 'Sign in', new_user_session_path %>
<%= link_to 'Sign up', new_user_registration_path %>
<% end %>
-->

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/search.html.erb
<!--<form action="films" method="get">
<p>Search <input type="text" name="search" size="30">
<input type="submit" value="Search" name="button1"></p>
</form>
-->
<br>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<% parameter = params[:q] %>
<% i = Spotlite::Search.new(parameter).movies %>
<table>
<thead>
     <tr>
      <th>Title</th>
      <th>Runtime</th>
      <th>Details</th>
     </tr>
</thead>
<tbody>


<% i.each do |filmarray| %>
<% film = Film.create(:cover => filmarray.poster_url, :title => filmarray.title, :runtime => filmarray.runtime, :release_date => filmarray.release_date, :plot => filmarray.description) %>

<% filmarray.cast[0..1].map do |hash| %>
<% actor_name = {name: hash[:name]} %>
 
<% act_name = Actor.find_by name: actor_name[:name] %> 
<% if act_name == nil %> 

<% actor = Actor.create(:name => actor_name[:name])%>
<% FilmActor.create(:film_id => film.id, :actor_id => actor.id) %>
<% else FilmActor.create(:film_id => film.id, :actor_id => act_name.id) %>
<% end %>
<% end %>

<% filmarray.directors.map do |hash| %>
<% director_name = {name: hash[:name]} %>

<% dir_name = Director.find_by name: director_name[:name] %>
<% if dir_name == nil %>

<% director = Director.create(:name => director_name[:name]) %>
<% FilmDirector.create(:film_id => film.id, :director_id => director.id) %>
<% else FilmDirector.create(:film_id => film.id, :director_id => dir_name.id) %>
<% end %>
<% end %>


<%filmarray.genres.each do |category_name| %>

<% cat_name = Category.find_by genre: category_name %>
<% if cat_name == nil %>

<% category = Category.create(:genre => category_name) %>
<% FilmCategory.create(:film_id => film.id, :category_id => category.id) %>
<% else FilmCategory.create(:film_id => film.id, :category_id => cat_name.id) %>
<% end %>
<% end %>

<tr><td align = left><%= filmarray.title %></td>
    <td align = center><%= filmarray.runtime %></td>
    <td><%= link_to 'Show', film %></td> 
</tr>
<% end %>



</tbody>
</table>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>
<table>
<tr>
  <td><strong>Title:</strong></td>
  <td><%= @film.title %></td>
</tr>
<tr>
  <td><strong>Cover:</strong></td>
  <td><%=image_tag @film.cover, :height=>'25%', :width=>'25%'%></td>
</tr>
<tr>
  <td><strong>Runtime:</strong></td>
  <td><%= @film.runtime %> min</td>
</tr>
<tr>
  <td><strong>Release date:</strong></td>
  <td><%= @film.release_date %></td>
</tr>
<tr>
  <td><strong>Actors:</strong>
  <td><% @film.actors.each do |actor| %>
  <%= actor.name %>,
  <% end %></td>
</tr>
<tr>
  <td><strong>Directors:</strong>
  <td><% @film.directors.each do |director| %>
  <%= director.name %>,
  <% end %></td>
</tr>
<tr>
  <td><strong>Genres:</strong>
  <td><% @film.categories.each do |genre| %>
  <%= genre.genre %>,
  <% end %></td>
</tr>
<tr>
  <td><strong>Plot:</strong></td>
  <td><%= @film.plot %></td>
</tr>
<tr>
  <td><strong>Rating:</strong></td>
  <td><%= rating_for @film, "rating" %></td>
</tr>
</table>
<br>

<% if user_session != nil %>
  <% if current_user.has_role? :admin %>
    <%= link_to 'Edit', edit_film_path(@film) %> |
  <% end %>
<% end %>
<table>
<tr>
<td>
<% if user_session != nil %>
<%= form_tag "/films/add_new_rental" do %>
<%= hidden_field_tag "id", @film.id %>
<%= submit_tag "Rent" %>
<% end %>
<% end %>
</td></tr>
<tr><td><br></td></tr>
<tr>
<td><%= link_to 'Back', films_path %></td>
</tr></table>

 <% if user_session != nil %> 
   <br><h2>Kommentiere den Film</h2>
   <%= form_tag "/films/add_new_comment" do %>
   <%= hidden_field_tag "id", @film.id %>               
   <table>
     <tr> 
       <td><strong>Titel:</strong></td><td><%= text_field_tag "comment[title]" %></td>
     </tr>
     <tr>  
       <td><strong>Kommentar:</strong></td><td><%= text_area_tag "comment[comment]" %></td>
     </tr> 
     <tr>
       <td><%= submit_tag "Post" %></td><td></td>
     </tr>
   </table>
  <% end %>                
  <% end %>
    
  <h3>Alle Kommentare (<%= @film.comments.find(:all).count %>)</h3>
  <table>
  <% @film.comments.each do |commentar| %>
    <tr>  
      <td>User:</td><td><%= commentar.user.email %></td>	
    </tr>
    <tr>  
      <td>Titel:</td><td><%= commentar.title %></td>
    </tr>  
    <tr>
      <td>Kommentar:</td><td><%= commentar.comment %></td>
    </tr>
    <tr>
      <td><strong>-----------------</strong></td><td></td>
    </tr>
  <% end %>
  </table>            